require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'


target 'TwillioTesting' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )
  
  pod 'Alamofire', '~> 5'
  pod 'AppCenter/Distribute', '~> 3'
  pod 'Firebase/Analytics', '~> 6'
  pod 'Firebase/Crashlytics', '~> 6'
  pod 'FirebaseUI/Auth', '~> 9'
  pod 'FirebaseUI/Google', '~> 9'
  pod 'IGListDiffKit', '~> 4'
  pod 'KeychainAccess', '~> 4'
  pod 'TwilioVideo', '~> 4'
  pod 'IGListKit', '~> 4.0.0'

  target 'TwillioTestingTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
